package com.example.examplemod.util;

import com.example.examplemod.recipe.properties.RecipePropertyLibrary;
import com.example.examplemod.recipe.properties.RecipePropertyState;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.items.ItemStackHandler;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Utility class for generating and exporting KubeJS recipe scripts.
 */
public class KubeJSExporter {

    /**
     * Generates a KubeJS recipe script from the given parameters.
     */
    public static String generateRecipeScript(String recipeType, String recipeId,
                                               ItemStackHandler inputs, ItemStackHandler outputs,
                                               int activeInputSlots, int activeOutputSlots,
                                               RecipePropertyState propertyState) {
        StringBuilder script = new StringBuilder();

        script.append("// Generated by Recipe Editor GUI\n");
        script.append("ServerEvents.recipes(event => {\n");
        script.append("  event.custom({\n");
        script.append("    type: \"").append(recipeType).append("\",\n");

        RecipePropertyState state = propertyState != null ? propertyState : new RecipePropertyState();
        RecipePropertyLibrary.appendSelectedProperties(script, state);
        script.append('\n');

        // Handle different recipe types
        String lowerType = recipeType.toLowerCase();

        if (lowerType.contains("shaped") || lowerType.contains("crafting_shaped")) {
            generateShapedCrafting(script, inputs, outputs, activeInputSlots, activeOutputSlots);
        } else if (lowerType.contains("shapeless") || lowerType.contains("crafting_shapeless")) {
            generateShapelessCrafting(script, recipeType, inputs, outputs, activeInputSlots, activeOutputSlots);
        } else if (lowerType.contains("smelting") || lowerType.contains("blasting") ||
                   lowerType.contains("smoking") || lowerType.contains("campfire")) {
            generateSmeltingRecipe(script, inputs, outputs, recipeType);
        } else if (lowerType.contains("stonecutting")) {
            generateStonecuttingRecipe(script, inputs, outputs);
        } else if (lowerType.contains("smithing")) {
            generateSmithingRecipe(script, inputs, outputs);
        } else {
            // Generic recipe format
            generateGenericRecipe(script, inputs, outputs, activeInputSlots, activeOutputSlots);
        }

        script.append("  }).id(\"kubejs:").append(recipeId).append("\");\n");
        script.append("});\n");

        return script.toString();
    }

    private static void generateShapedCrafting(StringBuilder script, ItemStackHandler inputs,
                                                ItemStackHandler outputs, int activeInputSlots, int activeOutputSlots) {
        script.append("        pattern: [\n");

        // Generate 3x3 pattern
        for (int row = 0; row < 3; row++) {
            script.append("            \"");
            for (int col = 0; col < 3; col++) {
                int index = row * 3 + col;
                ItemStack stack = inputs.getStackInSlot(index);
                if (!stack.isEmpty()) {
                    script.append((char) ('A' + index));
                } else {
                    script.append(' ');
                }
            }
            script.append("\"");
            if (row < 2) script.append(",");
            script.append("\n");
        }
        script.append("        ],\n");

        script.append("        key: {\n");
        for (int i = 0; i < 9; i++) {
            ItemStack stack = inputs.getStackInSlot(i);
            if (!stack.isEmpty()) {
                String itemId = getItemId(stack);
                script.append("            \"").append((char) ('A' + i)).append("\": { item: \"")
                      .append(itemId).append("\" }");

                // Add comma if not last
                boolean hasMore = false;
                for (int j = i + 1; j < 9; j++) {
                    if (!inputs.getStackInSlot(j).isEmpty()) {
                        hasMore = true;
                        break;
                    }
                }
                if (hasMore) script.append(",");
                script.append("\n");
            }
        }
        script.append("        },\n");

        // Add result
        if (activeOutputSlots > 0 && !outputs.getStackInSlot(0).isEmpty()) {
            ItemStack result = outputs.getStackInSlot(0);
            String itemId = getItemId(result);
            script.append("        result: { item: \"").append(itemId).append("\"");
            if (result.getCount() > 1) {
                script.append(", count: ").append(result.getCount());
            }
            script.append(" }\n");
        }
    }

    private static void generateShapelessCrafting(StringBuilder script, String recipeType, ItemStackHandler inputs,
                                                   ItemStackHandler outputs, int activeInputSlots, int activeOutputSlots) {
        script.append("    ingredients: [\n");

        for (int i = 0; i < activeInputSlots; i++) {
            ItemStack stack = inputs.getStackInSlot(i);
            if (!stack.isEmpty()) {
                String itemId = getItemId(stack);
                script.append("      { item: \"").append(itemId).append("\" }");

                // Check if there are more items
                boolean hasMore = false;
                for (int j = i + 1; j < activeInputSlots; j++) {
                    if (!inputs.getStackInSlot(j).isEmpty()) {
                        hasMore = true;
                        break;
                    }
                }
                if (hasMore) script.append(",");
                script.append("\n");
            }
        }
        script.append("    ],\n");

        // Add result
        if (activeOutputSlots > 0 && !outputs.getStackInSlot(0).isEmpty()) {
            ItemStack result = outputs.getStackInSlot(0);
            String itemId = getItemId(result);
            boolean isCraftingTableRecipe = recipeType.toLowerCase().contains("crafting");

            if (isCraftingTableRecipe) {
                script.append("    result: { item: \"").append(itemId).append("\"");
                if (result.getCount() > 1) {
                    script.append(", count: ").append(result.getCount());
                }
                script.append(" }\n");
            } else {
                script.append("    results: [\n");
                script.append("      { item: \"").append(itemId).append("\"");
                if (result.getCount() > 1) {
                    script.append(", count: ").append(result.getCount());
                }
                script.append(" }");
                script.append("\n    ]\n");
            }
        }
    }

    private static void generateSmeltingRecipe(StringBuilder script, ItemStackHandler inputs,
                                                ItemStackHandler outputs, String recipeType) {
        if (!inputs.getStackInSlot(0).isEmpty()) {
            String itemId = getItemId(inputs.getStackInSlot(0));
            script.append("        ingredient: { item: '").append(itemId).append("' },\n");
        }

        if (!outputs.getStackInSlot(0).isEmpty()) {
            String itemId = getItemId(outputs.getStackInSlot(0));
            script.append("        result: '").append(itemId).append("',\n");
        }

        // Add experience and cooking time defaults
        script.append("        experience: 0.1,\n");

        if (recipeType.contains("blasting")) {
            script.append("        cookingtime: 100\n");
        } else if (recipeType.contains("smoking")) {
            script.append("        cookingtime: 100\n");
        } else if (recipeType.contains("campfire")) {
            script.append("        cookingtime: 600\n");
        } else {
            script.append("        cookingtime: 200\n");
        }
    }

    private static void generateStonecuttingRecipe(StringBuilder script, ItemStackHandler inputs,
                                                     ItemStackHandler outputs) {
        if (!inputs.getStackInSlot(0).isEmpty()) {
            String itemId = getItemId(inputs.getStackInSlot(0));
            script.append("        ingredient: { item: '").append(itemId).append("' },\n");
        }

        if (!outputs.getStackInSlot(0).isEmpty()) {
            ItemStack result = outputs.getStackInSlot(0);
            String itemId = getItemId(result);
            script.append("        result: '").append(itemId).append("',\n");
            script.append("        count: ").append(result.getCount()).append("\n");
        }
    }

    private static void generateSmithingRecipe(StringBuilder script, ItemStackHandler inputs,
                                                ItemStackHandler outputs) {
        script.append("        base: ");
        if (!inputs.getStackInSlot(1).isEmpty()) {
            String itemId = getItemId(inputs.getStackInSlot(1));
            script.append("{ item: '").append(itemId).append("' }");
        } else {
            script.append("{ item: 'minecraft:air' }");
        }
        script.append(",\n");

        script.append("        addition: ");
        if (!inputs.getStackInSlot(2).isEmpty()) {
            String itemId = getItemId(inputs.getStackInSlot(2));
            script.append("{ item: '").append(itemId).append("' }");
        } else {
            script.append("{ item: 'minecraft:air' }");
        }
        script.append(",\n");

        script.append("        template: ");
        if (!inputs.getStackInSlot(0).isEmpty()) {
            String itemId = getItemId(inputs.getStackInSlot(0));
            script.append("{ item: '").append(itemId).append("' }");
        } else {
            script.append("{ item: 'minecraft:air' }");
        }
        script.append(",\n");

        if (!outputs.getStackInSlot(0).isEmpty()) {
            String itemId = getItemId(outputs.getStackInSlot(0));
            script.append("        result: { item: '").append(itemId).append("' }\n");
        }
    }

    private static void generateGenericRecipe(StringBuilder script, ItemStackHandler inputs,
                                               ItemStackHandler outputs, int activeInputSlots, int activeOutputSlots) {
        script.append("    ingredients: [\n");

        for (int i = 0; i < activeInputSlots; i++) {
            ItemStack stack = inputs.getStackInSlot(i);
            if (!stack.isEmpty()) {
                String itemId = getItemId(stack);
                script.append("      { item: \"").append(itemId).append("\" }");

                boolean hasMore = false;
                for (int j = i + 1; j < activeInputSlots; j++) {
                    if (!inputs.getStackInSlot(j).isEmpty()) {
                        hasMore = true;
                        break;
                    }
                }
                if (hasMore) script.append(",");
                script.append("\n");
            }
        }
        script.append("    ],\n");

        // Add outputs
        script.append("    results: [\n");
        for (int i = 0; i < activeOutputSlots; i++) {
            ItemStack stack = outputs.getStackInSlot(i);
            if (!stack.isEmpty()) {
                String itemId = getItemId(stack);
                script.append("      { item: \"").append(itemId).append("\",count: 1 }");

                boolean hasMore = false;
                for (int j = i + 1; j < activeOutputSlots; j++) {
                    if (!outputs.getStackInSlot(j).isEmpty()) {
                        hasMore = true;
                        break;
                    }
                }
                if (hasMore) script.append(",");
                script.append("\n");
            }
        }
        script.append("    ]\n");
    }

    private static String getItemId(ItemStack stack) {
        ResourceLocation id = BuiltInRegistries.ITEM.getKey(stack.getItem());
        return id.toString();
    }

    /**
     * Exports the script to a file in the kubejs/server_scripts directory.
     */
    public static boolean exportToFile(String script, String recipeId) {
        try {
            // Get the game directory
            File gameDir = new File(".");
            File kubeJSDir = new File(gameDir, "kubejs");
            File serverScriptsDir = new File(kubeJSDir, "server_scripts");

            // Create directories if they don't exist
            if (!serverScriptsDir.exists()) {
                serverScriptsDir.mkdirs();
            }

            // Write the script file
            File scriptFile = new File(serverScriptsDir, recipeId + ".js");
            try (FileWriter writer = new FileWriter(scriptFile)) {
                writer.write(script);
            }

            System.out.println("Recipe exported to: " + scriptFile.getAbsolutePath());
            return true;

        } catch (IOException e) {
            System.err.println("Failed to export recipe: " + e.getMessage());
            e.printStackTrace();
            return false;
        }
    }
}
